apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
spec:
  containers:
    - name: jellyfin
      image: docker.io/linuxserver/jellyfin:10.10.7

      ports:
        - containerPort: 8096
          hostPort: ${JELLYFIN_HTTP_PORT}
        - containerPort: 8920
          hostPort: ${JELLYFIN_HTTPS_PORT}

      env:
        - name: PUID
          value: "${PUID}"
        - name: PGID
          value: "${PGID}"
        - name: TZ
          value: "${TZ}"

      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /Media
          name: media

  volumes:
    - name: config
      hostPath:
        path: ${DATA_DIR}/config
    - name: media
      hostPath:
        path: ${MEDIA_DIR}